In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [71]:
df = pd.read_csv("../datasets/customer.csv")

In [72]:
df.sample(5)

,age,gender,review,education,purchased
49,25,Female,Good,UG,No
32,92,Male,Average,UG,Yes
2,70,Female,Good,PG,No
6,18,Male,Good,School,No
28,48,Male,Poor,School,No


In [73]:
df = df.iloc[:,2:]

we will transform the categorical data into numerical

In [74]:
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


## Train Test split

In [75]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [56]:
X_train

,review,education
15,Poor,UG
16,Poor,UG
11,Good,UG
28,Poor,School
32,Average,UG
38,Good,School
21,Average,PG
40,Good,School
12,Poor,School
13,Average,School


In [57]:
from sklearn.preprocessing import OrdinalEncoder

In [58]:
oe = OrdinalEncoder(categories=[["Poor","Average","Good"], ["School", "PG", "UG"]])

In [59]:
oe.fit(X_train)

,"categories categories: 'auto' or a list of array-like, default='auto'Categories (unique values) per feature:- 'auto' : Determine categories automatically from the training data.- list : ``categories[i]`` holds the categories expected in the ith column. The passed categories should not mix strings and numeric values, and should be sorted in case of numeric values.The used categories can be found in the ``categories_`` attribute.","[['Poor', 'Average', ...], ['School', 'PG', ...]]"
,"dtype dtype: number type, default=np.float64Desired dtype of output.",<class 'numpy.float64'>
,"handle_unknown handle_unknown: {'error', 'use_encoded_value'}, default='error'When set to 'error' an error will be raised in case an unknowncategorical feature is present during transform. When set to'use_encoded_value', the encoded value of unknown categories will beset to the value given for the parameter `unknown_value`. In:meth:`inverse_transform`, an unknown category will be denoted as None... versionadded:: 0.24",'error'
,"unknown_value unknown_value: int or np.nan, default=NoneWhen the parameter handle_unknown is set to 'use_encoded_value', thisparameter is required and will set the encoded value of unknowncategories. It has to be distinct from the values used to encode any ofthe categories in `fit`. If set to np.nan, the `dtype` parameter mustbe a float dtype... versionadded:: 0.24",None
,"encoded_missing_value encoded_missing_value: int or np.nan, default=np.nanEncoded value of missing categories. If set to `np.nan`, then the `dtype`parameter must be a float dtype... versionadded:: 1.1",nan
,"min_frequency min_frequency: int or float, default=NoneSpecifies the minimum frequency below which a category will beconsidered infrequent.- If `int`, categories with a smaller cardinality will be considered infrequent.- If `float`, categories with a smaller cardinality than `min_frequency * n_samples` will be considered infrequent... versionadded:: 1.3 Read more in the :ref:`User Guide `.",None
,"max_categories max_categories: int, default=NoneSpecifies an upper limit to the number of output categories for each inputfeature when considering infrequent categories. If there are infrequentcategories, `max_categories` includes the category representing theinfrequent categories along with the frequent categories. If `None`,there is no limit to the number of output features.`max_categories` do **not** take into account missing or unknowncategories. Setting `unknown_value` or `encoded_missing_value` to aninteger will increase the number of unique integer codes by one each.This can result in up to `max_categories + 2` integer codes... versionadded:: 1.3 Read more in the :ref:`User Guide `.",None


In [60]:
X_train.dtypes

review       object
education    object
dtype: object

In [61]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [62]:
X_train

array([[0., 2.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [1., 2.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [1., 0.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 2.],
       [2., 1.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 1.],
       [1., 2.],
       [1., 1.],
       [1., 2.],
       [1., 0.],
       [2., 2.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [1., 2.],
       [2., 2.],
       [0., 1.]])

In [63]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'PG', 'UG']]

## Label Encoding

This encoder should be used to encode target values and not the input X

In [64]:
from sklearn.preprocessing import LabelEncoder

In [65]:
le = LabelEncoder()

In [66]:
le.fit(y_train)

LabelEncoder()

In [67]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [76]:
y_train

26     No
10    Yes
23     No
31    Yes
13     No
0      No
18     No
39     No
5     Yes
14    Yes
28     No
3      No
49     No
17    Yes
41    Yes
48    Yes
9     Yes
35    Yes
1      No
8      No
6      No
40     No
4      No
27     No
44     No
47    Yes
15     No
7     Yes
30     No
21     No
33    Yes
37    Yes
11    Yes
42    Yes
20    Yes
32    Yes
46     No
22    Yes
36    Yes
16    Yes
Name: purchased, dtype: object

In [77]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [78]:
y_train


array([0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1])

## One Hot Encoding, Categorical Data

we have to transform the categorial data into numberical b/c ML algos only accept numeric data

we will work with a color dataset. It has no order, so its nominal data. If we have 50 diferent columns then we need to create 50 columns. They will becomes vectors.

### Dumpy Variable Trap

After doing one hot encoding, we remove the first column eg if we have n columns. we remove one so finally we have n-1

We remove the columns due to the concept knows as multi colinearity. There is a mathematical corelation b/w these columns.

They are dependent on each other. In ML, the input colums must be independent. 

Y is the dependent column b/c it depends on x columns

when doing OHE. We can reduce the dimensionality of the data. lets say we have a dataset with 40 cars. Out of them, only 10 brands 
have the most numbe of cars and others have very little data. we can squeeze all of them into a single column. This way we can have
10 columns instead of 40

In [101]:
df = pd.read_csv("../datasets/cars.csv", encoding="latin1")

In [102]:
df.head()

,brand,km_driven,fuel,owner,selling_price
0,Maruti,145500,Diesel,First Owner,450000
1,Skoda,120000,Diesel,Second Owner,370000
2,Honda,140000,Petrol,Third Owner,158000
3,Hyundai,127000,Diesel,First Owner,225000
4,Maruti,120000,Petrol,First Owner,130000


In [103]:
df["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [104]:
df["brand"].nunique()

32

In [105]:
df["fuel"].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [106]:
df["fuel"].nunique()

4

In [107]:
pd.get_dummies(df["brand"],["company"])

,['company']_Ambassador,['company']_Ashok,['company']_Audi,['company']_BMW,['company']_Chevrolet,['company']_Daewoo,['company']_Datsun,['company']_Fiat,['company']_Force,['company']_Ford,...,['company']_Mitsubishi,['company']_Nissan,['company']_Opel,['company']_Peugeot,['company']_Renault,['company']_Skoda,['company']_Tata,['company']_Toyota,['company']_Volkswagen,['company']_Volvo
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8124,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False


## K-1 One Hot Encoding

In [108]:
pd.get_dummies(df,columns=["fuel", "brand"],drop_first=True)

,km_driven,owner,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,...,brand_Mitsubishi,brand_Nissan,brand_Opel,brand_Peugeot,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo
0,145500,First Owner,450000,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,120000,Second Owner,370000,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,140000,Third Owner,158000,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,127000,First Owner,225000,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,120000,First Owner,130000,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,110000,First Owner,320000,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8124,119000,Fourth & Above Owner,135000,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8125,120000,First Owner,382000,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8126,25000,First Owner,290000,True,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False


now we want to append brand , company names with train new column

we don't use pandas for this b/c they don't remember which column to keep. so we use scikit learn one hot encoder class

## One hot encoding - Sklearn

In [111]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1], test_size=0.2, random_state=0)

In [112]:
X_train.head()

,brand,km_driven,fuel,owner
3042,Hyundai,60000,LPG,First Owner
1520,Tata,150000,Diesel,Third Owner
2611,Hyundai,110000,Diesel,Second Owner
3544,Mahindra,28000,Diesel,Second Owner
4138,Maruti,15000,Petrol,First Owner


In [113]:
X_test.head()

,brand,km_driven,fuel,owner
3558,Hyundai,40000,Diesel,First Owner
233,Mahindra,70000,Diesel,First Owner
7952,Maruti,5000,Petrol,First Owner
572,Maruti,120000,Petrol,Third Owner
6960,Lexus,20000,Petrol,First Owner


In [116]:
from sklearn.preprocessing import OneHotEncoder


In [136]:
ohe = OneHotEncoder(drop="first", sparse_output=False, dtype= np.int32, handle_unknown="ignore") # cut first column
# handle unknown here b/c some brand that was in the test data was never in the train data


In [137]:
X_train_new = ohe.fit_transform(X_train[["fuel", "brand"]])

In [138]:
X_test_new = ohe.transform(X_test[["fuel", "brand"]])


/Users/mycomputer/.pyenv/versions/3.12.3/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:261: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)


In [139]:
X_train_new

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 0],
       [0, 0, 1, ..., 0, 0, 0]], dtype=int32)

In [140]:
np.hstack ((X_train[["fuel", "brand"]].values, X_train_new)).shape

(6502, 35)

## 4. One Hot Encoding with Top Categories

This replaces brands with ≤100 occurrences as "uncommon" before encoding. 

In [142]:
counts = df["brand"].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [143]:
df['brand'].nunique()

32

In [146]:
threshold = 100 
repl = counts[counts <= threshold].index

In [149]:
new = pd.get_dummies(df['brand'].replace(repl,'uncommon'))

In [150]:
new.shape

(8128, 13)